# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flutter_Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flutter_Test

end
 

#新添加的代码
flutter_application_path = '../flutterlib'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
